name: test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      # - name: Check PowerShell
      #   run: $PSVersionTable
      - name : Checkout repository
        uses: actions/checkout@v3